"""sprint16_advanced_config

Revision ID: 165d62cdaba4
Revises: d5e6f7a8b9c0
Create Date: 2026-05-01 11:53:20.150078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '165d62cdaba4'
down_revision: Union[str, None] = 'd5e6f7a8b9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connectors', sa.Column('advanced_config', sa.JSON(), nullable=True))
    op.create_index('ix_executions_connector_created', 'executions', ['connector_id', 'created_at'], unique=False)
    op.drop_constraint(op.f('sso_domain_hints_domain_key'), 'sso_domain_hints', type_='unique')
    op.drop_index(op.f('ix_sso_domain_hints_domain'), table_name='sso_domain_hints')
    op.create_index(op.f('ix_sso_domain_hints_domain'), 'sso_domain_hints', ['domain'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sso_domain_hints_domain'), table_name='sso_domain_hints')
    op.create_index(op.f('ix_sso_domain_hints_domain'), 'sso_domain_hints', ['domain'], unique=False)
    op.create_unique_constraint(op.f('sso_domain_hints_domain_key'), 'sso_domain_hints', ['domain'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_executions_connector_created', table_name='executions')
    op.drop_column('connectors', 'advanced_config')
    # ### end Alembic commands ###
